# This workflow builds and publishes the latest docs to
# the `gh-pages` branch.
# For more details: https://github.com/marketplace/actions/deploy-to-github-pages
name: Publish docs

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        # fetch all tags so `versioneer` can properly determine current version
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: '3.11'
    - name: Install pandoc
      uses: pandoc/actions/setup@86321b6dd4675f5014c611e05088e10d4939e09e # v1
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements-ml.txt
        pip install -r requirements-reports.txt
        pip install -r requirements-docs.txt
        pip install -e .

    - name: Build
      run: |
        cd _docs/docs
        python update_documentation.py
    - name: Publish
      uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445 # v4.9.0
      with:
        branch: gh-pages
        folder: _docs/docs/LATEST/html
