# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Python Package

on:
  pull_request:
    branches:
      - 'main'
      - 'feature/**'
      - 'dev'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-ml.txt ]; then pip install -r requirements-ml.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
        if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
        if [ -f requirements-reports.txt ]; then pip install -r requirements-reports.txt; fi
    - name: run pre-commit
      run: |
        pre-commit install
        pre-commit run --all-files
    - name: Test with pytest
      run: |
        DATAPROFILER_SEED=0 pytest --forked --cov=dataprofiler --cov-fail-under=80
